version: '3'
services:
  redash-server:
    image: redash/redash:latest
    command: dev_server
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    env_file:
      - docker/env/.redash.env
    environment:
      PYTHONUNBUFFERED: 0

  redash-scheduler:
    image: redash/redash:latest
    command: dev_scheduler
    depends_on:
      - redash-server
    env_file:
      - docker/env/.redash.env

  redash-worker:
    image: redash/redash:latest
    command: dev_worker
    depends_on:
      - redash-server
    env_file:
      - docker/env/.redash.env
    environment:
      PYTHONUNBUFFERED: 0

  redis:
    image: redis:3.0-alpine
    restart: unless-stopped

  email:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - "1080:80"
